events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # Ensure .wasm files are served with correct MIME type
        location ~* \.wasm$ {
            root /usr/share/nginx/html;
            add_header Content-Type application/wasm;
        }
    }
}
